language: node_js
node_js:
  - 'node'

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+/

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: deploy
      script: yarn publish
      if: tag IS present

cache:
  yarn: true
  directories:
    - node_modules
