language: node_js
node_js:
  - '11'
  - '10'
  - '9'
  - '8'

branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+\.[0-9]+/

script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: deploy
      node_js: '11'
      script: npm-publish-git-tag
      if: tag IS present

cache:
  yarn: true
  directories:
    - node_modules
